//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLogistics.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_delivery
    {
        public int id { get; set; }
        public int ORDER_ID { get; set; }
        public System.DateTime delivery_date { get; set; }
        public string delivery_plate { get; set; }
        public string delivery_person { get; set; }
    
        public virtual tbl_order tbl_order { get; set; }
    }
}
