//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLogistics.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_order()
        {
            this.tbl_delivery = new HashSet<tbl_delivery>();
        }
    
        public int id { get; set; }
        public string order_no { get; set; }
        public System.DateTime create_date { get; set; }
        public string shipment_poit { get; set; }
        public string receiver { get; set; }
        public string contact_phone { get; set; }
        public int PRODUCT_ID { get; set; }
        public int order_count { get; set; }
        public short order_transfer_status { get; set; }
        public Nullable<System.DateTime> order_transfer_status_update_date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_delivery> tbl_delivery { get; set; }
        public virtual tbl_product tbl_product { get; set; }
    }
}
