//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALogistics.Console.WCFDataTransfer.OrderService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Response", Namespace="http://schemas.datacontract.org/2004/07/BLogistics.Core.Helper")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ALogistics.Console.WCFDataTransfer.OrderService.ResponseOfArrayOfOrderT0qgZqbZ))]
    public partial class Response : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ALogistics.Console.WCFDataTransfer.OrderService.EnumListWCFResponseMessageType ResponseStatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ALogistics.Console.WCFDataTransfer.OrderService.EnumListWCFResponseMessageType ResponseStatus {
            get {
                return this.ResponseStatusField;
            }
            set {
                if ((this.ResponseStatusField.Equals(value) != true)) {
                    this.ResponseStatusField = value;
                    this.RaisePropertyChanged("ResponseStatus");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseOfArrayOfOrderT0qgZqbZ", Namespace="http://schemas.datacontract.org/2004/07/BLogistics.Core.Helper")]
    [System.SerializableAttribute()]
    public partial class ResponseOfArrayOfOrderT0qgZqbZ : ALogistics.Console.WCFDataTransfer.OrderService.Response {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ALogistics.Console.WCFDataTransfer.OrderService.Order[] ResultField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ALogistics.Console.WCFDataTransfer.OrderService.Order[] Result {
            get {
                return this.ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultField, value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EnumList.WCFResponseMessageType", Namespace="http://schemas.datacontract.org/2004/07/BLogistics.Core.Enum")]
    public enum EnumListWCFResponseMessageType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Order", Namespace="http://schemas.datacontract.org/2004/07/BLogistics.Core.DTO")]
    [System.SerializableAttribute()]
    public partial class Order : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PRODUCT_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string contact_phoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime create_dateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int order_countField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string order_noField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short order_transfer_statusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> order_transfer_status_update_dateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ALogistics.Console.WCFDataTransfer.OrderService.Product productField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string receiverField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string shipment_poitField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PRODUCT_ID {
            get {
                return this.PRODUCT_IDField;
            }
            set {
                if ((this.PRODUCT_IDField.Equals(value) != true)) {
                    this.PRODUCT_IDField = value;
                    this.RaisePropertyChanged("PRODUCT_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string contact_phone {
            get {
                return this.contact_phoneField;
            }
            set {
                if ((object.ReferenceEquals(this.contact_phoneField, value) != true)) {
                    this.contact_phoneField = value;
                    this.RaisePropertyChanged("contact_phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime create_date {
            get {
                return this.create_dateField;
            }
            set {
                if ((this.create_dateField.Equals(value) != true)) {
                    this.create_dateField = value;
                    this.RaisePropertyChanged("create_date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int order_count {
            get {
                return this.order_countField;
            }
            set {
                if ((this.order_countField.Equals(value) != true)) {
                    this.order_countField = value;
                    this.RaisePropertyChanged("order_count");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string order_no {
            get {
                return this.order_noField;
            }
            set {
                if ((object.ReferenceEquals(this.order_noField, value) != true)) {
                    this.order_noField = value;
                    this.RaisePropertyChanged("order_no");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short order_transfer_status {
            get {
                return this.order_transfer_statusField;
            }
            set {
                if ((this.order_transfer_statusField.Equals(value) != true)) {
                    this.order_transfer_statusField = value;
                    this.RaisePropertyChanged("order_transfer_status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> order_transfer_status_update_date {
            get {
                return this.order_transfer_status_update_dateField;
            }
            set {
                if ((this.order_transfer_status_update_dateField.Equals(value) != true)) {
                    this.order_transfer_status_update_dateField = value;
                    this.RaisePropertyChanged("order_transfer_status_update_date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ALogistics.Console.WCFDataTransfer.OrderService.Product product {
            get {
                return this.productField;
            }
            set {
                if ((object.ReferenceEquals(this.productField, value) != true)) {
                    this.productField = value;
                    this.RaisePropertyChanged("product");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string receiver {
            get {
                return this.receiverField;
            }
            set {
                if ((object.ReferenceEquals(this.receiverField, value) != true)) {
                    this.receiverField = value;
                    this.RaisePropertyChanged("receiver");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string shipment_poit {
            get {
                return this.shipment_poitField;
            }
            set {
                if ((object.ReferenceEquals(this.shipment_poitField, value) != true)) {
                    this.shipment_poitField = value;
                    this.RaisePropertyChanged("shipment_poit");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="http://schemas.datacontract.org/2004/07/BLogistics.Core.DTO")]
    [System.SerializableAttribute()]
    public partial class Product : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime create_dateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string product_barcodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string product_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int stock_countField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime create_date {
            get {
                return this.create_dateField;
            }
            set {
                if ((this.create_dateField.Equals(value) != true)) {
                    this.create_dateField = value;
                    this.RaisePropertyChanged("create_date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string product_barcode {
            get {
                return this.product_barcodeField;
            }
            set {
                if ((object.ReferenceEquals(this.product_barcodeField, value) != true)) {
                    this.product_barcodeField = value;
                    this.RaisePropertyChanged("product_barcode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string product_name {
            get {
                return this.product_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.product_nameField, value) != true)) {
                    this.product_nameField = value;
                    this.RaisePropertyChanged("product_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int stock_count {
            get {
                return this.stock_countField;
            }
            set {
                if ((this.stock_countField.Equals(value) != true)) {
                    this.stock_countField = value;
                    this.RaisePropertyChanged("stock_count");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OrderService.IOrderService")]
    public interface IOrderService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderService/OrderList", ReplyAction="http://tempuri.org/IOrderService/OrderListResponse")]
        ALogistics.Console.WCFDataTransfer.OrderService.ResponseOfArrayOfOrderT0qgZqbZ OrderList(System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderService/OrderList", ReplyAction="http://tempuri.org/IOrderService/OrderListResponse")]
        System.Threading.Tasks.Task<ALogistics.Console.WCFDataTransfer.OrderService.ResponseOfArrayOfOrderT0qgZqbZ> OrderListAsync(System.DateTime date);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOrderServiceChannel : ALogistics.Console.WCFDataTransfer.OrderService.IOrderService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OrderServiceClient : System.ServiceModel.ClientBase<ALogistics.Console.WCFDataTransfer.OrderService.IOrderService>, ALogistics.Console.WCFDataTransfer.OrderService.IOrderService {
        
        public OrderServiceClient() {
        }
        
        public OrderServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OrderServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ALogistics.Console.WCFDataTransfer.OrderService.ResponseOfArrayOfOrderT0qgZqbZ OrderList(System.DateTime date) {
            return base.Channel.OrderList(date);
        }
        
        public System.Threading.Tasks.Task<ALogistics.Console.WCFDataTransfer.OrderService.ResponseOfArrayOfOrderT0qgZqbZ> OrderListAsync(System.DateTime date) {
            return base.Channel.OrderListAsync(date);
        }
    }
}
