//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALogistics.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_order_delivey
    {
        public int id { get; set; }
        public Nullable<int> ORDER_ID { get; set; }
        public short delivery_status { get; set; }
        public string delivery_plate { get; set; }
        public string delivery_person { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
    
        public virtual tbl_external_order tbl_external_order { get; set; }
    }
}
