//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALogistics.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_external_order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_external_order()
        {
            this.tbl_order_delivey = new HashSet<tbl_order_delivey>();
        }
    
        public int id { get; set; }
        public string order_no { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public string shipment_poit { get; set; }
        public string receiver { get; set; }
        public string contact_phone { get; set; }
        public Nullable<int> order_count { get; set; }
        public string product_name { get; set; }
        public string product_barcode { get; set; }
        public Nullable<int> stock_count { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_order_delivey> tbl_order_delivey { get; set; }
    }
}
